gnosis/safe-ios

bin/bootstrap.sh
bin/git/hooks/commit-msg

@MouazAlzahabi @sche after this is merged, please pull from master and run the bootstrap script:
```
$> bin/bootstrap.sh
```
This will install the git hook. The git commit hook will take the "gh-XXX" portion of your branch name and prepend it to the commit message automatically.
closes #34

gh-34  added hooks

---

Multisig/UI/ENS/ENSNameLoader.swift
Multisig/UI/ENS/EnterENSNameViewModel.swift
Multisig/UI/Safe Management/Load Safe/EnterSafeAddress/EnterSafeAddressViewModel.swift
Multisig/UI/Safe Management/Safe Settings/SafeSettingsViewModel.swift

gh-53  fixing

---

Multisig/UI/App/RootNavigationView.swift
Multisig/UI/Safe Management/Safe Selector/SelectedSafeButton.swift
Multisig/UI/UI Library/SafeCell.swift

gh-72  fixed the name length in the navbar

---

Multisig/UI/UI Library/PopupView.swift

gh-75  moved tap to the background of popup

---

Multisig.xcodeproj/project.pbxproj
Multisig/UI/App/RootNavigationView.swift
Multisig/UI/Safe Management/Safe Info/CenteredAddressWithLink.swift
Multisig/UI/Safe Management/Safe Selector/SelectedSafeButton.swift
Multisig/UI/Safe Management/Safe Selector/SwitchSafeButton.swift
Multisig/UI/Safe Management/Switch Safe/SwitchSafeView.swift
Multisig/UI/UI Library/Frame/FrameForNavigationBar.swift
Multisig/UI/UI Library/Frame/FrameForTapping.swift
Multisig/UI/UI Library/SafeCell.swift

fixes #55 
This branch is taken off the gh-72

Gh 55 navbar tappable areas

---

Multisig/UI/ENS/EnterENSNameView.swift
Multisig/UI/Safe Management/Load Safe/EnterSafeAddress/EnterSafeAddressView.swift

gh-63  confirm made bold

---

Multisig.xcodeproj/project.pbxproj
Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameView.swift
Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameViewModel.swift
Multisig/UI/UI Library/BackButton.swift

gh-71  changed the edit name screen

---

Multisig/UI/Safe Management/Load Safe/AddSafeIntroView.swift

gh-152  fixed navigation of load safe

---

Multisig/UI/Settings/Get In Touch/EmailSupportViewController.swift

gh-158  fixing navbar color of email vc

---

Multisig/UI/App/ContentView.swift
Multisig/UI/Safe Management/Safe Selector/SelectedSafeButton.swift
Multisig/UI/UI Library/SafeCell.swift
Multisig/UI/UI Library/Styleguide/Icons.swift

gh-153  no safes loaded ui

---

Multisig.xcodeproj/project.pbxproj

gh-160  bump deployment target to 13.4

---

Multisig.xcodeproj/project.pbxproj
Multisig/UI/Safe Management/Load Safe/EnterSafeName/EnterSafeNameView.swift
Multisig/UI/UI Library/KeyboardAdaptive.swift

gh-100  added keyboard adaptive behavior to safe name screen

---

Multisig.xcodeproj/project.pbxproj
Multisig/Cross-layer/App.swift
Multisig/Data/Persistence/CoreDataProtocol.swift
Multisig/Data/Persistence/CoreDataStack.swift
Multisig/Logic/Models/AppSettings.swift
Multisig/Logic/Models/Safe.swift
Multisig/Logic/Models/Selection.swift
Multisig/UI/App/SceneDelegate.swift
Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameView.swift
Multisig/UI/Safe Management/Safe Selector/SafeHeaderView.swift
Multisig/UI/Safe Management/Switch Safe/SwitchSafeView.swift
Multisig/UI/Settings/Get In Touch/EmailSupportViewController.swift
MultisigTests/Data/Persistence/CoreDataTestCase.swift
MultisigTests/Data/Persistence/TestCoreDataStack.swift
MultisigTests/Logic/Models/AppSettingsTests.swift
MultisigTests/Logic/Models/SafeTests.swift

gh-145 fix unit tests spoiling app database

---

Jenkinsfile

Seems that it fixed the "log in" part, now we need to see if we need to bump the master's build version.

gh-81  comment

---

Jenkinsfile
README.md
bin/configure.sh

Added using the environment variable for the secret key

gh-86  added using environment key

---

Jenkinsfile
Multisig/Info.plist
MultisigIntegrationTests/Info.plist
MultisigTests/Info.plist

gh-86  changed archive artifacts

---

Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameViewModel.swift
Multisig/UI/Safe Management/Load Safe/EnterSafeName/EnterSafeNameViewModel.swift

Gh 235/ws safe name

---

Multisig.xcodeproj/project.pbxproj
Multisig/Cross-layer/App.swift
Multisig/UI/App/MainTabView.swift
Multisig/UI/App/MainView.swift
Multisig/UI/App/ViewState.swift
Multisig/UI/Safe Management/Load Safe/EnterSafeAddress/EnterSafeAddressView.swift
Multisig/UI/Transactions/TransactionsList/TransactionListView.swift
Multisig/UI/Transactions/TransactionsList/TransactionsView.swift
Multisig/UI/Transactions/TransactionsList/TransactionsViewModel.swift
Multisig/UI/UI Library/RemoveSafeButton.swift

Only the transactions tab, because I couldn't resolve the same issue in the "top tab view". Stays for the "Data reloading" epic.

gh-239  preventing view redraw triggering the request

---

Multisig/UI/UI Library/Frame/FrameForNavigationBar.swift

Don't mess with the NavigationView, they said 😆

gh-192  that fixed it

---

Jenkinsfile
Multisig/Data/Services/SafeRelayService.swift
Multisig/Logic/Ethereum/Utils/Data+InitWithHex.swift
Multisig/Logic/Models/Address.swift
Multisig/Logic/Models/Transaction/DataString.swift
Multisig/UI/Assets/BalancesView.swift
Multisig/UI/Transactions/TransactionConfirmationsView/TransactionConfirmationViewModel.swift
Multisig/UI/Transactions/TransactionHeaderView/TransferValueView.swift
Multisig/UI/Transactions/TransactionViewModel/TransferTransactionViewModel.swift
Multisig/UI/Transactions/TransactionsList/TransactionsViewModel.swift
Multisig/UI/UI Library/TokenImage.swift

Bug fixes 272, 273, 274, 275
